---

- hosts: all
  become: true
  tasks:

  - name: add php support, net tools and apache2
    apt:
      name:
        - libapache2-mod-php
        - apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
