- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    # File name of src and html/filename.html can be different. The files from src are copied to html/filename.html even if the name is different
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
